GardenyaGirisimciKadinlar/Models/ShoppingCart.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GardenyaGirisimciKadinlar.Models
{
    public class ShoppingCart
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        string ShoppingCartId { get; set; }
        public const string CartSessionKey = "CartId";
        public static ShoppingCart GetCart(HttpContextBase context)
        {
            var cart = new ShoppingCart();
            cart.ShoppingCartId = cart.GetCartId(context);
            return cart;
        }
        // Helper method to simplify shopping cart calls
        public static ShoppingCart GetCart(Controller controller)
        {
            return GetCart(controller.HttpContext);
        }
        public void AddToCart(Urunler Urunler)
        {
            //Urunler Urunler =  db.Urunlers.Where(x => x.UrunID == Urun.UrunID).FirstOrDefault();
             
            // Get the matching cart and album instances
            var cartItem = db.Carts.SingleOrDefault(
                c => c.CartID == ShoppingCartId
                && c.UrunID == Urunler.UrunID);

            if (cartItem == null)
            {
                // Create a new cart item if no cart item exists
                cartItem = new Cart
                {
                    UrunID = Urunler.UrunID,
                    CartID = ShoppingCartId,
                    Count = Urunler.Adet,
                    DateCreated = DateTime.Now
                };
                db.Carts.Add(cartItem);
            }
            else
            {
                // If the item does exist in the cart, 
                // then add one to the quantity
                cartItem.Count+=Urunler.Adet;
            }
            // Save changes
            db.SaveChanges();
        }
        public int RemoveFromCart(int id)
        {
            // Get the cart
            var cartItem = db.Carts.Single(
                cart => cart.CartID == ShoppingCartId
                && cart.RecordID == id);

            int itemCount = 0;

            if (cartItem != null)
            {
                if (cartItem.Count > 1)
                {
                    cartItem.Count--;
                    itemCount = cartItem.Count;
                }
                else
                {
                    db.Carts.Remove(cartItem);
                }
                // Save changes
                db.SaveChanges();
            }
            return itemCount;
        }
        public void EmptyCart()
        {
            var cartItems = db.Carts.Where(
                cart => cart.CartID == ShoppingCartId);

            foreach (var cartItem in cartItems)
            {
                db.Carts.Remove(cartItem);
            }
            // Save changes
            db.SaveChanges();
        }
        public List<Cart> GetCartItems()
        {
            var result = db.Carts.Where(
                cart => cart.CartID == ShoppingCartId).ToList();
            foreach (var item in result)
            {
                item.SubTotal = item.Count * item.Urunler.Fiyat;
            }
            return result;
        }
        //public List<ShoppingCardViewModel> cartAraTplm(Cart liste)
        //{
        //   var cartt= db.Carts.Where(
        //        cart => cart.CartID == ShoppingCartId).ToList();
        //    var aratplm=new List<ShoppingCardViewModel>();
        //    foreach (var item in cartt)
        //    {
               
        //        aratplm.CartAraToplam = item.Count * item.Urunler.Fiyat;
        //    }
        //    return aratplm;
        //}
        public int GetCount()
        {
            // Get the count of each item in the cart and sum them up
            int? count = (from cartItems in db.Carts
                          where cartItems.CartID == ShoppingCartId
                          select (int?)cartItems.Count).Sum();
            // Return 0 if all entries are null
            return count ?? 0;
        }
        public decimal GetTotal()
        {
            // Multiply album price by count of that album to get 
            // the current price for each of those albums in the cart
            // sum all album price totals to get the cart total
            decimal? total = (from cartItems in db.Carts
                              where cartItems.CartID == ShoppingCartId
                              select (int?)cartItems.Count *
                              cartItems.Urunler.Fiyat).Sum();

            return total ?? decimal.Zero;
        }
        public int CreateSiparis(Siparis Siparis)
        {
            decimal SiparisTotal = 0;

            var cartItems = GetCartItems();
            // Iterate over the items in the cart, 
            // adding the Siparis details for each
            foreach (var item in cartItems)
            {
                var SiparisDetail = new SiparisDetay
                {
                    UrunID = item.UrunID,
                    SiparisID = Siparis.SiparisID,
                    Adet = item.Urunler.Fiyat,
                    Fiyat = item.Count
                };
                // Set the Siparis total of the shopping cart
                SiparisTotal += (item.Count * item.Urunler.Fiyat);

                db.SiparisDetays.Add(SiparisDetail);

            }
            // Set the Siparis's total to the SiparisTotal count
            Siparis.Total = SiparisTotal;

            // Save the Siparis
            db.SaveChanges();
            // Empty the shopping cart
            EmptyCart();
            // Return the SiparisId as the confirmation number
            return Siparis.SiparisID;
        }
        // We're using HttpContextBase to allow access to cookies.
        public string GetCartId(HttpContextBase context)
        {
            if (context.Session[CartSessionKey] == null)
            {
                if (!string.IsNullOrWhiteSpace(context.User.Identity.Name))
                {
                    context.Session[CartSessionKey] =
                        context.User.Identity.Name;
                }
                else
                {
                    // Generate a new random GUID using System.Guid class
                    Guid tempCartId = Guid.NewGuid();
                    // Send tempCartId back to client as a cookie
                    context.Session[CartSessionKey] = tempCartId.ToString();
                }
            }
            return context.Session[CartSessionKey].ToString();
        }
        // When a user has logged in, migrate their shopping cart to
        // be associated with their username
        public void MigrateCart(string userName)
        {
            var shoppingCart = db.Carts.Where(
                c => c.CartID == ShoppingCartId);

            foreach (Cart item in shoppingCart)
            {
                item.CartID = userName;
            }
            db.SaveChanges();
        }
    }
}

GardenyaGirisimciKadinlar/Controllers/ShoppingCartController.cs
using GardenyaGirisimciKadinlar.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GardenyaGirisimciKadinlar.Controllers
{
    public class ShoppingCartController : Controller
    {
        // GET: ShoppingCart
        private ApplicationDbContext db = new ApplicationDbContext();
        public ActionResult Index()
        {
            //View modelimle çalışıp bana bilgi verecek
            var cart = ShoppingCart.GetCart(this.HttpContext);
            var cartviewmodel = new ShoppingCardViewModel
            {
                CartItems = cart.GetCartItems(),
                CartTotal = cart.GetTotal(),

            };

           
            return View(cartviewmodel);
        }
        //addCart
        public ActionResult AddToCart([Bind(Include = "UrunID,Adet")] Urunler urunler)
        {
            var eklenen = db.Urunlers.FirstOrDefault(x => x.UrunID == urunler.UrunID);
            eklenen.Adet = urunler.Adet;
            var cart = ShoppingCart.GetCart(this.HttpContext);
            cart.AddToCart(eklenen);
            return RedirectToAction("Index");

        }
        //RemoveCart
        public ActionResult RemoveToCart(int id)
        {
            //item countu değişti
            //total amount değişti
            //view model mesaj vermiştik bunu da gönderelim

            //var kaldir = db.Products.FirstOrDefault(x => x.ProductID == id).ProductID;
            var cart = ShoppingCart.GetCart(this.HttpContext);
            //Kullanıcıya mesaj vermek istiyorum
            //şu isimli ürün sepetinizden kaldırıldı gibi
            //o yüzden şunu yazmam gerekecek
            string itemname = db.Carts.FirstOrDefault(x => x.RecordID == id).Urunler.Baslik;//Ürünün adını getirmek için yazdık

            int itemcount = cart.RemoveFromCart(id);
            var result = new ShoppingCartRemoveViewModel
            {
                Message = Server.HtmlEncode(itemname) + " sepetinizden başarıyla kaldırıldı",
                CartTotal = cart.GetTotal(),
                Count = cart.GetCount(),
                ItemCount = itemcount
            };
            return Json(result);

        }
        //Cart Summary
        //Partial view olabilir
        public ActionResult CartSummary()
        {
            var cart = ShoppingCart.GetCart(this.HttpContext);
            ViewData["CartCount"] = cart.GetCount();
            return PartialView("CartSummary");
        }
    }
}

GardenyaGirisimciKadinlar/Controllers/SiparisController.cs
using GardenyaGirisimciKadinlar.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GardenyaGirisimciKadinlar.Controllers
{
    public class SiparisController : Controller
    {
        // GET: Siparis
        public ActionResult SiparisTamamla(Cart cart )
        {
            if (User.Identity.IsAuthenticated)
            {

                return View();
            }
            else {
                 return View("Login","Account");
            }
          
        }
    }
}

GardenyaGirisimciKadinlar/Views/ShoppingCart/CartSummary.cshtml
@Html.ActionLink("Sepetim(" + ViewData["CartCount"] + ")", "Index", "ShoppingCart", new { id = "cart-status" })

GardenyaGirisimciKadinlar/Views/ShoppingCart/Index.cshtml
@model GardenyaGirisimciKadinlar.Models.ShoppingCardViewModel

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script type="text/javascript" src="~/Scripts/jquery-3.3.1.min.js"></script>
@* Add to cart yada remove kart yaptığımda sepeti güncelleme işlemi jquery olmalı *@
<script type="text/javascript">
    $(function () {
        $(".RemoveLink").click(function () {
            //Linkteki id yi yakalamak için
            var silinecekid = $(this).attr("data-id");
            if (silinecekid != '') {
                //null değilse post işlemi başlamalı
                $.post("/ShoppingCart/RemoveToCart", { "id": silinecekid },
                    //eğer başarılıysa post
                    function (data) {
                        //sepeti güncelle
                        if (data.ItemCount == 0) {
                            $("#item-count-" + data.Deleteid).fadeOut('slow');
                        } else {
                            $("#item-count-" + data.Deleteid).text(data.ItemCount);
                        }
                        $("$cart-total").text(data.CartTotal);
                        $("#update-message").text(data.Message);
                        $("#cart-status").text('Cart(' + data.CartCount + ')');
                    }
                )
            }
            //$("#cartdetail").load("/ShoppingCart/Index/");
            location.reload();
        });
    });

    //$(function () {
    //    $("#count").click(function () {
    //        var count = document.getElementById("#count").value;
    //        var fiyat = document.getElementById("#fiyat").value;
            
    //        document.getElementById("#araFiyat").value = count * fiyat;
    //    });
    //    });

</script>

<section class="cart-section spad">
    <div class="container">
        <div class="row">
            <div class="col-lg-8">
                <div class="cart-table">
                    <h3>Sepetim</h3>
                    <div class="cart-table-warp">
                        <table>
                            <thead>
                                <tr>
                                    <th class="product-th">Ürün Adı</th>
                                    <th class="quy-th">Adet</th>
                                    <th class="size-th">Ara Toplam</th>
                                    <th class="total-th"></th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model.CartItems)
                                {
                                    <tr id="row-@item.RecordID">
                                        <td class="product-col">
                                            <img src="../@Html.DisplayFor(modelItem => item.Urunler.Resim)" alt="">
                                            <div class="pc-title">
                                                <h4> @Html.DisplayFor(modelItem => item.Urunler.Baslik)</h4>
                                                <p> @Html.DisplayFor(modelItem => item.Urunler.Fiyat)<span class="simge-tl">&#8378;</span></p>
                                            </div>
                                        </td>
                                        <td class="quy-col">
                                            <div class="quantity">
                                                <div class="pro-qty">
                                                    <input type="text" value="@Html.DisplayFor(modelItem => item.Count)"  >
                                                </div>
                                            </div>
                                        </td>
                                        <td class="size-col"><h4>@Html.DisplayFor(modelItem => item.SubTotal )<span class="simge-tl">&#8378;</span></h4></td>
                                        <td class="total-col">
                                            <a href="#" class="RemoveLink btn " data-id="@item.RecordID">
                                                İptal Et
                                            </a><h4></h4>
                                        </td>
                                    </tr>
                                }
                                </tbody>
                        </table>
                    </div>
                    <div class="total-cost">
                        <h6>Toplam <span>@Model.CartTotal</span></h6>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 card-right">

                @*<a href="" class="site-btn">Siparişi Tamamla</a>*@
                @Html.ActionLink("Siparişi Tamamla", "SiparisiTamamla","Siparis", new { model=Model }, new { @class = "site-btn" })
                <a href="/Home/Index" class="site-btn sb-dark">Alışverişe Devam Et</a>
            </div>
        </div>
    </div>
</section>