GardenyaGirisimciKadinlar/Models/Kategori.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace GardenyaGirisimciKadinlar.Models
{
    public class Kategori
    {
        [Key]
        public int KategoriID { get; set; }
        [Required]
        public string KategoriAdi { get; set; }
        public string KategoriLink { get; set; }
        public virtual List<AltKategori> AltKategoris { get; set; }
    }
}

GardenyaGirisimciKadinlar/Controllers/KategorisController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using GardenyaGirisimciKadinlar.Models;

namespace GardenyaGirisimciKadinlar.Controllers
{
    public class KategorisController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Kategoris
        [Authorize(Roles = "Admin")]
        public ActionResult Index()
        {
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Login", "Account");
            }
            return View(db.Kategoris.ToList());
        }

        // GET: Kategoris/Details/5
        [Authorize(Roles = "Admin")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                if (ViewBag.KID == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                else
                {
                    id = ViewBag.KID;
                }
            }
            Kategori kategori = db.Kategoris.Find(id);
            if (kategori == null)
            {
                return HttpNotFound();
            }
            ViewBag.KID = id;
            ViewBag.KAD = kategori.KategoriAdi;
            return View(kategori);
        }
        [Authorize(Roles = "Admin")]
        public ActionResult AltKategoriPartial(int? id)
        {
            if (id == null)
            {
                if (ViewBag.KID == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                else
                {
                    id = ViewBag.KID;
                }
            }
            var result = (from k in db.Kategoris
                          join ak in db.AltKategoris on k.KategoriID equals ak.KategoriID
                          where ak.KategoriID == id
                          select new KategoriAltkategoriViewModel
                          {
                           AltKategoriID=    ak.AltKategoriID,
                              AltKategoriAdi= ak.AltKategoriAdi,
                              AltKategoriLink=ak.AltKategoriLink,
                              KategoriAdi=k.KategoriAdi,
                             KategoriID= ak.KategoriID
                          }).ToList();
            var ad = db.Kategoris.Where(x => x.KategoriID == id).FirstOrDefault();
            ViewBag.KID = id;
            ViewBag.KAD = ad.KategoriAdi;
            return PartialView(result);
        }
        [Authorize(Roles = "Admin")]
        public ActionResult AltKategoriEkle(int? id)
        {
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Login", "Account");
            }
            if (id == null)
            {
                if (ViewBag.KID==null)
                {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                else
                {
                    id = ViewBag.KID;
                }
                
            }
            var result = (from k in db.Kategoris
                          
                          where k.KategoriID == id
                          select new KategoriAltkategoriViewModel
                          {
                             KategoriAdi=k.KategoriAdi,
                             KategoriID= k.KategoriID
                          }).FirstOrDefault();
            ViewBag.KID = id;
            ViewBag.KAD = result.KategoriAdi;
            return View(result);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AltKategoriEkle(KategoriAltkategoriViewModel altk)
        {
            AltKategori alt = new AltKategori();
            alt.AltKategoriAdi = altk.AltKategoriAdi;
            alt.AltKategoriLink = altk.AltKategoriLink;
            alt.KategoriID = altk.KategoriID;
            db.AltKategoris.Add(alt);
            db.SaveChanges();
            ViewBag.KID = altk.KategoriID;
            ViewBag.KAD = altk.KategoriAdi;
            return View("Details");
        }
        // GET: Kategoris/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Login", "Account");
            }
            return View();
        }
        [Authorize(Roles = "Admin")]
        public ActionResult AltKategoriDuzenle(int? id,int? kid)
        {
            if (kid == null)
            {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var altkategori  = db.AltKategoris.Where(x=>x.AltKategoriID==kid).FirstOrDefault();
            Kategori kategori = db.Kategoris.Find(id);
            if (altkategori == null)
            {
                return HttpNotFound();
            }
            ViewBag.KAD = kategori.KategoriAdi;
            ViewBag.KID = kategori.KategoriID;
            return View(altkategori);
        }
        [HttpPost]
           public ActionResult AltKategoriDuzenle([Bind(Include = "AltKategoriID,AltKategoriAdi,AltKategoriLink")]AltKategori altkategori)
        {
            AltKategori alt = db.AltKategoris.Where(x => x.AltKategoriID == altkategori.AltKategoriID).FirstOrDefault();
            alt.AltKategoriAdi = altkategori.AltKategoriAdi;
            alt.AltKategoriLink = altkategori.AltKategoriLink;
            
            db.SaveChanges();

            Kategori kategori = db.Kategoris.Where(x=>x.KategoriID== alt.KategoriID).FirstOrDefault();
            if (altkategori == null)
            {
                return HttpNotFound();
            }
            ViewBag.KAD = kategori.KategoriAdi;
            ViewBag.KID = kategori.KategoriID;
            return View("Details");
        }
        [HttpPost]
        public ActionResult AltKategoriSil(int? kid)
        {
            if (kid == null)
            {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            AltKategori altkategori = db.AltKategoris.Find(kid);
            db.AltKategoris.Remove(altkategori);
            db.SaveChanges();
            ViewBag.KID = altkategori.KategoriID;
            Kategori ktgr = db.Kategoris.Where(x => x.KategoriID == altkategori.KategoriID).FirstOrDefault();
            ViewBag.KAD = ktgr.KategoriAdi;
            return View("Details");
        }
        [Authorize(Roles = "Admin")]
        public ActionResult AltKategoriSil(int? id, int? kid)
        {
            if (kid == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            AltKategori altkategori = db.AltKategoris.Find(kid);
            Kategori kategori = db.Kategoris.Find(id);
            if (altkategori == null)
            {
                return HttpNotFound();
            }

           
            ViewBag.KAD = kategori.KategoriAdi;
            ViewBag.KID = kategori.KategoriID;
            return View(altkategori);
        }

        // POST: Kategoris/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "KategoriID,KategoriAdi,KategoriLink")] Kategori kategori)
        {
            if (ModelState.IsValid)
            {
                db.Kategoris.Add(kategori);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(kategori);
        }

        // GET: Kategoris/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Kategori kategori = db.Kategoris.Find(id);
            if (kategori == null)
            {
                return HttpNotFound();
            }
            return View(kategori);
        }

        // POST: Kategoris/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "KategoriID,KategoriAdi,KategoriLink")] Kategori kategori)
        {
            if (ModelState.IsValid)
            {
                db.Entry(kategori).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(kategori);
        }

        // GET: Kategoris/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Kategori kategori = db.Kategoris.Find(id);
            if (kategori == null)
            {
                return HttpNotFound();
            }
            return View(kategori);
        }

        // POST: Kategoris/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Kategori kategori = db.Kategoris.Find(id);
            db.Kategoris.Remove(kategori);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

GardenyaGirisimciKadinlar/Views/Kategoris/AltKategoriDuzenle.cshtml
@model GardenyaGirisimciKadinlar.Models.AltKategori

@{
    ViewBag.Title = "AltKategoriDuzenle";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="col-lg-6 " style="margin-left:30px !important;">
    <h3 class="fw-title">Kategori Düzenle</h3>
    <hr />

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>AltKategori</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.AltKategoriID)

            <div class="form-group">
                @Html.LabelFor(model => model.AltKategoriAdi, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.AltKategoriAdi, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.AltKategoriAdi, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.AltKategoriLink, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.AltKategoriLink, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.AltKategoriLink, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                Kategori Adı
                <div class="col-md-10">
                    @ViewBag.KAD
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="site-btn" />
                </div>
            </div>
        </div>
    }


</div>
<div>
    @Html.ActionLink("Alt Kategoriler Listesi", "Details", new { id = ViewBag.KID })
</div>

GardenyaGirisimciKadinlar/Views/Kategoris/AltKategoriEkle.cshtml
@model GardenyaGirisimciKadinlar.Models.KategoriAltkategoriViewModel

@{
    /**/

    ViewBag.Title = "AltKategoriEkle";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


<h3 class="fw-title">@Html.DisplayFor(model => model.KategoriAdi)</h3>
<br />

@using (Html.BeginForm(new { @class = "contact-form" }))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.KategoriID)
<div style="margin-top:50px !important;">
    <h5>Alt Kategori Ekle</h5>
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.AltKategoriAdi, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.AltKategoriAdi, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.AltKategoriAdi, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.AltKategoriLink, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.AltKategoriLink, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.AltKategoriLink, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Ekle" class="site-btn" />
        </div>
    </div>
</div>

}<div>
    @Html.ActionLink("Alt Kategoriler Listesi", "Details", new { id = ViewBag.KID })
</div>

GardenyaGirisimciKadinlar/Views/Kategoris/AltKategoriPartial.cshtml
@model IEnumerable<GardenyaGirisimciKadinlar.Models.KategoriAltkategoriViewModel>

<div style="margin-top:50px !important">
    <h4>Alt Kategoriler</h4>

    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.AltKategoriAdi)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AltKategoriLink)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.KategoriAdi)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(model => item.AltKategoriAdi)
                </td>
                <td>
                    @Html.DisplayFor(model => item.AltKategoriLink)
                </td>
                <td>
                    @Html.DisplayFor(model => item.KategoriAdi)
                </td>
                <td>
                    @Html.ActionLink("Düzenle", "AltKategoriDuzenle", new { id = item.KategoriID, kid = item.AltKategoriID }) |
                    @Html.ActionLink("Sil", "AltKategoriSil", new { id = item.KategoriID, kid = item.AltKategoriID })
                </td>
            </tr>

        }

        <tr>
            <td></td>
            <td></td>
            <td></td>
            <td>

                @Html.ActionLink("Alt Kategori Oluştur", "AltKategoriEkle", new { id = ViewBag.KID })
            </td>
        </tr>

    </table>

</div>

GardenyaGirisimciKadinlar/Views/Kategoris/AltKategoriSil.cshtml
@model GardenyaGirisimciKadinlar.Models.AltKategori

@{
    ViewBag.Title = "AltKategoriSil";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="col-lg-6 " style="margin-left:30px !important;">
    <h3 class="fw-title">AltKategori Sil</h3>
    <br />
    <br />
    <h6>Silmek istediğinize emin misiniz?</h6>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.AltKategoriAdi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AltKategoriAdi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AltKategoriLink)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AltKategoriLink)
        </dd>

        <dt>
            Kategori Adı
        </dt>

        <dd>
            @ViewBag.KAD
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Sil" class="site-btn" /> |

            @Html.ActionLink("Alt Kategoriler Listesi", "Details", new { id = Model.KategoriID })
        </div>
    }
</div>

GardenyaGirisimciKadinlar/Views/Kategoris/Create.cshtml
@model GardenyaGirisimciKadinlar.Models.Kategori

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


<div class="col-lg-6 " style="margin-left:30px !important;">
    <h3 class="fw-title">Kategori Oluştur</h3>
    <hr />
    @using (Html.BeginForm(new { @class = "contact-form" }))
    {
        @Html.AntiForgeryToken()



        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.KategoriAdi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.KategoriAdi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.KategoriAdi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.KategoriLink, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.KategoriLink, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.KategoriLink, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Ekle" class="site-btn" />
            </div>
        </div>

    }<div>
        @Html.ActionLink("Kategoriler Listesi", "Index")
    </div>
</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

GardenyaGirisimciKadinlar/Views/Kategoris/Delete.cshtml
@model GardenyaGirisimciKadinlar.Models.Kategori

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


<div class="col-lg-6 " style="margin-left:30px !important;">
    <h3 class="fw-title">Kategori Sil</h3>
    <br />
    <br />
    <h6>Silmek istediğinize emin misiniz?</h6>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.KategoriAdi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.KategoriAdi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.KategoriLink)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.KategoriLink)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Sil" class="site-btn" /> |
            @Html.ActionLink("Kategori Listesi", "Index")
        </div>
    }
</div>

GardenyaGirisimciKadinlar/Views/Kategoris/Details.cshtml
@model GardenyaGirisimciKadinlar.Models.Kategori

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h3 class="fw-title">@ViewBag.KAD</h3>
<br />
@{
    Html.RenderAction("AltKategoriPartial", "Kategoris", new { id = ViewBag.KID });
}
<div>
    @Html.ActionLink("Kategoriler Listesi", "Index")
</div>

GardenyaGirisimciKadinlar/Views/Kategoris/Edit.cshtml
@model GardenyaGirisimciKadinlar.Models.Kategori

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="col-lg-6 " style="margin-left:30px !important;">
    <h3 class="fw-title">Kategori Düzenle</h3>
    <hr />
    @using (Html.BeginForm(new { @class = "contact-form" }))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">

            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.KategoriID)

            <div class="form-group">
                @Html.LabelFor(model => model.KategoriAdi, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.KategoriAdi, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.KategoriAdi, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.KategoriLink, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.KategoriLink, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.KategoriLink, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Kaydet" class="site-btn" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Kategoriler Listesi", "Index")
    </div>
</div>
    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }

GardenyaGirisimciKadinlar/Views/Kategoris/Index.cshtml
@model IEnumerable<GardenyaGirisimciKadinlar.Models.Kategori>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h3 class="fw-title">Kategoriler</h3>
<br />
<br />
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.KategoriAdi)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.KategoriLink)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.KategoriAdi)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.KategoriLink)
            </td>
            <td>
                @Html.ActionLink("Düzenle", "Edit", new { id = item.KategoriID }) |
                @if (item.KategoriAdi != "Anasayfa")
                {
                    @Html.ActionLink("Sil", "Delete", new { id = item.KategoriID })<span>&nbsp;|</span>
                } 

                @Html.ActionLink("Alt Kategoriler", "Details", new { id = item.KategoriID })
            </td>
        </tr>
    }

</table>
<div>
    @Html.ActionLink("Kategori Oluştur", "Create")
</div>