GardenyaGirisimciKadinlar/Controllers/UrunlersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using GardenyaGirisimciKadinlar.Models;
using Microsoft.AspNet.Identity;

namespace GardenyaGirisimciKadinlar.Controllers
{
    public class UrunlersController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Urunlers
        [Authorize(Roles = "Admin")]
        public ActionResult TumUrunler()
        {
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Login", "Account");
            }
            var urunlers = db.Urunlers.Include(u => u.AltKategori);

            return View(urunlers.ToList());
        }
        [Authorize(Roles = "Girisimci")]
        public ActionResult Index()
        {
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Login", "Account");
            }
            var userid = User.Identity.GetUserId();
            

            var urunlers = db.Urunlers.Where(x=>x.GirisimciID==userid).ToList();
            return View(urunlers.ToList());
        }

        // GET: Urunlers/Details/5
        [Authorize(Roles = "Girisimci")]
        public ActionResult Details(int? id)
        {

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Urunler urunler = db.Urunlers.Find(id);
            string rsm = "../" + urunler.Resim;
            ViewBag.Resim = rsm;
            if (urunler == null)
            {
                return HttpNotFound();
            }
            return View(urunler);
        }

        // GET: Urunlers/Create
        [Authorize(Roles = "Girisimci")]
        public ActionResult Create()
        {
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Login", "Account");
            }
            ViewBag.AltKategoriID = new SelectList(db.AltKategoris, "AltKategoriID", "AltKategoriAdi");
            //var userid = User.Identity.GetUserId();

            return View();
        }

        // POST: Urunlers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "UrunID,Baslik,Aciklama,Adet,Fiyat,AltKategoriID")] Urunler urunler, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                if (file != null)
                {
                    WebImage img = new WebImage(file.InputStream);
                    FileInfo fotoinfo = new FileInfo(file.FileName);
                    string newfoto = Guid.NewGuid().ToString() + fotoinfo.Extension;
                    img.Resize(500, 775);
                    img.Save("~/Upload/Products/" + newfoto);
                    urunler.Resim = "../Upload/Products/" + newfoto;
                    urunler.EklenmeTarihi = DateTime.Now;

                }
                var userid = User.Identity.GetUserId();
                urunler.GirisimciID =userid;

                db.Urunlers.Add(urunler);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.AltKategoriID = new SelectList(db.AltKategoris, "AltKategoriID", "AltKategoriAdi", urunler.AltKategoriID);
            return View(urunler);
        }

        // GET: Urunlers/Edit/5
        [Authorize(Roles = "Girisimci")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Urunler urunler = db.Urunlers.Find(id);
            if (urunler == null)
            {
                return HttpNotFound();
            }
            ViewBag.AltKategoriID = new SelectList(db.AltKategoris, "AltKategoriID", "AltKategoriAdi", urunler.AltKategoriID);
            return View(urunler);
        }

        // POST: Urunlers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "UrunID,Baslik,Aciklama,Adet,Fiyat,EklenmeTarihi,AltKategoriID")] Urunler urunler, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                if (file != null && file.ContentLength>0)
                {
                    WebImage img = new WebImage(file.InputStream);
                    FileInfo fotoinfo = new FileInfo(file.FileName);
                    string newfoto = Guid.NewGuid().ToString() + fotoinfo.Extension;
                    img.Resize(500, 775);
                    img.Save("~/Upload/Products/" + newfoto);
                    urunler.Resim = "../Upload/Products/" + newfoto;

                }
                var userid = User.Identity.GetUserId();
                urunler.GirisimciID = userid;
                db.Entry(urunler).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.AltKategoriID = new SelectList(db.AltKategoris, "AltKategoriID", "AltKategoriAdi", urunler.AltKategoriID);
            return View(urunler);
        }

        // GET: Urunlers/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Urunler urunler = db.Urunlers.Find(id);
            string rsm = "../" + urunler.Resim;
            ViewBag.Resim =rsm ;
            if (urunler == null)
            {
                return HttpNotFound();
            }
            return View(urunler);
        }

        // POST: Urunlers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Urunler urunler = db.Urunlers.Find(id);
            db.Urunlers.Remove(urunler);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

GardenyaGirisimciKadinlar/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title | Gardenya</title>
    <!-- Favicon -->
    <link href="~/Content/img/favicon.ico" rel="shortcut icon" />

    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css?family=Josefin+Sans:300,300i,400,400i,700,700i" rel="stylesheet">


    <!-- Stylesheets -->
    <link rel="stylesheet" href="~/Content/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/Content/css/font-awesome.min.css" />
    <link rel="stylesheet" href="~/Content/css/flaticon.css" />
    <link rel="stylesheet" href="~/Content/css/slicknav.min.css" />
    <link rel="stylesheet" href="~/Content/css/jquery-ui.min.css" />
    <link rel="stylesheet" href="~/Content/css/owl.carousel.min.css" />
    <link rel="stylesheet" href="~/Content/css/animate.css" />
    <link rel="stylesheet" href="~/Content/css/style.css" />


    <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>
<body>
    <!-- Page Preloder -->
    <div id="preloder">
        <div class="loader"></div>
    </div>

    <!-- Header section -->
    <header class="header-section">
        <div class="header-top">
            <div class="container">
                <div class="row">
                    <div class="col-lg-2 text-center text-lg-left">
                        <!-- logo -->
                        <a href="./index.html" class="site-logo">

                            <img src="~/Content/img/logo.jpg" width="550" height="50" />
                        </a>
                    </div>
                    <div class="col-xl-6 col-lg-5 admin">
                        <h2>Yönetim Paneli</h2>
                    </div>
                    <div class="col-xl-4 col-lg-5">
                        <div class="user-panel">

                            @{
                                @Html.Partial("_LoginPartial")
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </header>
    <section class="category-section spad2">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 order-2 order-lg-1" style="margin-right:20px !important">
                    <div class="filter-widget">

                        <ul class="category-menu">
                            <li>
                                @Html.ActionLink("Anasayfa", "Home")
                            </li>
                            <li>
                                @Html.ActionLink("Girişimciler", "GirisimciListe","Liste")
                            </li>
                            <li>
                                @Html.ActionLink("Kullanıcılar", "KullaniciListe","Liste")
                            </li>
                            <li>@Html.ActionLink("Kategoriler", "../Kategoris")</li>
                            <li>@Html.ActionLink("Ürünler", "TumUrunler","Urunlers")</li>
                            <li>@Html.ActionLink("Siparişler", "Home")</li>
                        </ul>
                    </div>
                </div>
                <div class="page-top-info">
                    <div class="container">
                        <h6>@Html.ActionLink("Tema Görünümü","Index", "Home")</h6>

                    </div>
                </div>
                <div class="col-lg-8  order-2 order-lg-2 mb-5 mb-lg-0">
                    <div class="row">
                        @RenderBody()
                    </div>
                </div>
            </div>
        </div>
    </section>
    <section class="footer-section">
        <div class="social-links-warp">
            <div class="container">
                <div class="social-links">
                    <a href="" class="instagram"><i class="fa fa-instagram"></i><span>instagram</span></a>
                    <a href="" class="google-plus"><i class="fa fa-google-plus"></i><span>g+plus</span></a>
                    <a href="" class="pinterest"><i class="fa fa-pinterest"></i><span>pinterest</span></a>
                    <a href="" class="facebook"><i class="fa fa-facebook"></i><span>facebook</span></a>
                    <a href="" class="twitter"><i class="fa fa-twitter"></i><span>twitter</span></a>
                    <a href="" class="youtube"><i class="fa fa-youtube"></i><span>youtube</span></a>
                    <a href="" class="tumblr"><i class="fa fa-tumblr-square"></i><span>tumblr</span></a>
                </div>

                <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                <p class="text-white text-center mt-5">
                    Copyright &copy;
                    <script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
                </p>
                <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->

            </div>
        </div>
    </section>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <script src="~/Scripts/js/jquery-3.2.1.min.js"></script>
    <script src="~/Scripts/js/bootstrap.min.js"></script>
    <script src="~/Scripts/js/jquery.slicknav.min.js"></script>
    <script src="~/Scripts/js/owl.carousel.min.js"></script>
    <script src="~/Scripts/js/jquery.nicescroll.min.js"></script>
    <script src="~/Scripts/js/jquery.zoom.min.js"></script>
    <script src="~/Scripts/js/jquery-ui.min.js"></script>
    <script src="~/Scripts/js/main.js"></script>
</body>
</html>

GardenyaGirisimciKadinlar/Views/Shared/_GirisimciLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title | Gardenya</title>
    <!-- Favicon -->
    <link href="~/Content/img/favicon.ico" rel="shortcut icon" />

    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css?family=Josefin+Sans:300,300i,400,400i,700,700i" rel="stylesheet">


    <!-- Stylesheets -->
    <link rel="stylesheet" href="~/Content/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/Content/css/font-awesome.min.css" />
    <link rel="stylesheet" href="~/Content/css/flaticon.css" />
    <link rel="stylesheet" href="~/Content/css/slicknav.min.css" />
    <link rel="stylesheet" href="~/Content/css/jquery-ui.min.css" />
    <link rel="stylesheet" href="~/Content/css/owl.carousel.min.css" />
    <link rel="stylesheet" href="~/Content/css/animate.css" />
    <link rel="stylesheet" href="~/Content/css/style.css" />
    <link href="~/Content/login/css/main.css" rel="stylesheet" media="all">

    <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>
<body>
    <!-- Page Preloder -->
    <div id="preloder">
        <div class="loader"></div>
    </div>

    <!-- Header section -->
    <header class="header-section">
        <div class="header-top">
            <div class="container">
                <div class="row">
                    <div class="col-lg-2 text-center text-lg-left">
                        <!-- logo -->
                        <a href="./index.html" class="site-logo">

                            <img src="~/Content/img/logo.jpg" width="550" height="50" />
                        </a>
                    </div>
                    <div class="col-xl-6 col-lg-5 admin">
                        <h2>Girişimci Paneli</h2>
                    </div>
                    <div class="col-xl-4 col-lg-5">
                        <div class="user-panel">

                            @{
                                @Html.Partial("_LoginPartial")
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <section class="category-section spad2">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 order-2 order-lg-1" style="margin-right:20px !important">
                    <div class="filter-widget">

                        <ul class="category-menu">
                            @*<li>
            @Html.ActionLink("Anasayfa", "Home")
        </li>*@
                            <li>@Html.ActionLink("Profilim","GProfil", "Liste")</li>
                            <li>
                                @Html.ActionLink("Ürünlerim", "Index", "Urunlers")
                            </li>
                            <li>
                                @Html.ActionLink("Siparişlerim", "Home")
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="page-top-info">
                    <div class="container">
                        <h6>@Html.ActionLink("Tema Görünümü", "Index", "Home")</h6>
                        @*<div class="site-pagination">
                                <a href="">Home</a> /
                                <a href="">Shop</a> /
                            </div>*@
                    </div>
                </div>
                <div class="col-lg-8  order-2 order-lg-2 mb-5 mb-lg-0">
                    <div class="row">
                        @RenderBody()
                    </div>
                </div>
            </div>
        </div>
    </section>
    <section class="footer-section">
        <div class="social-links-warp">
            <div class="container">
                <div class="social-links">
                    <a href="" class="instagram"><i class="fa fa-instagram"></i><span>instagram</span></a>
                    <a href="" class="google-plus"><i class="fa fa-google-plus"></i><span>g+plus</span></a>
                    <a href="" class="pinterest"><i class="fa fa-pinterest"></i><span>pinterest</span></a>
                    <a href="" class="facebook"><i class="fa fa-facebook"></i><span>facebook</span></a>
                    <a href="" class="twitter"><i class="fa fa-twitter"></i><span>twitter</span></a>
                    <a href="" class="youtube"><i class="fa fa-youtube"></i><span>youtube</span></a>
                    <a href="" class="tumblr"><i class="fa fa-tumblr-square"></i><span>tumblr</span></a>
                </div>

                <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                <p class="text-white text-center mt-5">
                    Copyright &copy;
                    <script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
                </p>
                <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->

            </div>
        </div>
    </section>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <script src="~/Scripts/js/jquery-3.2.1.min.js"></script>
    <script src="~/Scripts/js/bootstrap.min.js"></script>
    <script src="~/Scripts/js/jquery.slicknav.min.js"></script>
    <script src="~/Scripts/js/owl.carousel.min.js"></script>
    <script src="~/Scripts/js/jquery.nicescroll.min.js"></script>
    <script src="~/Scripts/js/jquery.zoom.min.js"></script>
    <script src="~/Scripts/js/jquery-ui.min.js"></script>
    <script src="~/Scripts/js/main.js"></script>
    <script src="~/Content/login/js/global.js"></script>
    <script src="~/Content/login/js/global-file.js"></script>
</body>
</html>

GardenyaGirisimciKadinlar/Views/Shared/_KategoriLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title | Gardenya</title>
    <!-- Favicon -->
    <link href="~/Content/img/favicon.ico" rel="shortcut icon" />

    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css?family=Josefin+Sans:300,300i,400,400i,700,700i" rel="stylesheet">


    <!-- Stylesheets -->
    <link rel="stylesheet" href="~/Content/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/Content/css/font-awesome.min.css" />
    <link rel="stylesheet" href="~/Content/css/flaticon.css" />
    <link rel="stylesheet" href="~/Content/css/slicknav.min.css" />
    <link rel="stylesheet" href="~/Content/css/jquery-ui.min.css" />
    <link rel="stylesheet" href="~/Content/css/owl.carousel.min.css" />
    <link rel="stylesheet" href="~/Content/css/animate.css" />
    <link rel="stylesheet" href="~/Content/css/style.css" />
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.5.6/angular.js"></script>

    <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>
<body>
    <!-- Page Preloder -->
    <div id="preloder">
        <div class="loader"></div>
    </div>

    <!-- Header section -->
    <header class="header-section">
        <div class="header-top">
            <div class="container">
                <div class="row">
                    <div class="col-lg-2 text-center text-lg-left">
                        <!-- logo -->
                        <a href="./index.html" class="site-logo">

                            <img src="~/Content/img/logo.jpg" width="550" height="50" />
                        </a>
                    </div>
                    <div class="col-xl-6 col-lg-5">
                        <form class="header-search-form">
                            <input type="text" placeholder="Ne arıyordunuz..." id="ara">
                            <button><i class="flaticon-search"></i></button>
                        </form>
                    </div>
                    <div class="col-xl-4 col-lg-5">
                        <div class="user-panel">

                            @{
                                @Html.Partial("_LoginPartial")
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
        @{ Html.RenderAction("Menu", "Home"); }
    </header>
    @RenderBody()
    @*burayı kontrol et
        
        <section class="category-section spad2">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 order-2 order-lg-1" style="margin-right:20px !important">
                    <div class="filter-widget">


                        @Html.Partial("AltKategoriler")
                    </div>
                </div>

                <div class="col-lg-8  order-2 order-lg-2 mb-5 mb-lg-0">
                    <div class="row">
                        @RenderBody()
                    </div>
                </div>
            </div>
        </div>
    </section>*@
    <section class="footer-section">
        <div class="social-links-warp">
            <div class="container">
                <div class="social-links">
                    <a href="" class="instagram"><i class="fa fa-instagram"></i><span>instagram</span></a>
                    <a href="" class="google-plus"><i class="fa fa-google-plus"></i><span>g+plus</span></a>
                    <a href="" class="pinterest"><i class="fa fa-pinterest"></i><span>pinterest</span></a>
                    <a href="" class="facebook"><i class="fa fa-facebook"></i><span>facebook</span></a>
                    <a href="" class="twitter"><i class="fa fa-twitter"></i><span>twitter</span></a>
                    <a href="" class="youtube"><i class="fa fa-youtube"></i><span>youtube</span></a>
                    <a href="" class="tumblr"><i class="fa fa-tumblr-square"></i><span>tumblr</span></a>
                </div>

                <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                <p class="text-white text-center mt-5">
                    Copyright &copy;
                    <script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
                </p>
                <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->

            </div>
        </div>
    </section>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <script src="~/Scripts/js/jquery-3.2.1.min.js"></script>
    <script src="~/Scripts/js/bootstrap.min.js"></script>
    <script src="~/Scripts/js/jquery.slicknav.min.js"></script>
    <script src="~/Scripts/js/owl.carousel.min.js"></script>
    <script src="~/Scripts/js/jquery.nicescroll.min.js"></script>
    <script src="~/Scripts/js/jquery.zoom.min.js"></script>
    <script src="~/Scripts/js/jquery-ui.min.js"></script>
    <script src="~/Scripts/js/main.js"></script>
</body>
</html>

GardenyaGirisimciKadinlar/Views/Shared/_KullaniciLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title | Gardenya</title>
    <!-- Favicon -->
    <link href="~/Content/img/favicon.ico" rel="shortcut icon" />

    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css?family=Josefin+Sans:300,300i,400,400i,700,700i" rel="stylesheet">


    <!-- Stylesheets -->
    <link rel="stylesheet" href="~/Content/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/Content/css/font-awesome.min.css" />
    <link rel="stylesheet" href="~/Content/css/flaticon.css" />
    <link rel="stylesheet" href="~/Content/css/slicknav.min.css" />
    <link rel="stylesheet" href="~/Content/css/jquery-ui.min.css" />
    <link rel="stylesheet" href="~/Content/css/owl.carousel.min.css" />
    <link rel="stylesheet" href="~/Content/css/animate.css" />
    <link rel="stylesheet" href="~/Content/css/style.css" />
    <link href="~/Content/login/css/main.css" rel="stylesheet" media="all">

    <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>
<body>
    <!-- Page Preloder -->
    <div id="preloder">
        <div class="loader"></div>
    </div>

    <!-- Header section -->
    <header class="header-section">
        <div class="header-top">
            <div class="container">
                <div class="row">
                    <div class="col-lg-2 text-center text-lg-left">
                        <!-- logo -->
                        <a href="./index.html" class="site-logo">

                            <img src="~/Content/img/logo.png" />
                        </a>
                    </div>
                    <div class="col-xl-6 col-lg-5 admin">
                        <h2>Kullanıcı Paneli</h2>
                    </div>
                    <div class="col-xl-4 col-lg-5">
                        <div class="user-panel">

                            @{
                                @Html.Partial("_LoginPartial")
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <section class="category-section spad2">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 order-2 order-lg-1" style="margin-right:20px !important">
                    <div class="filter-widget">

                        <ul class="category-menu">
                            @*<li>
                                    @Html.ActionLink("Anasayfa", "Home")
                                </li>*@
                            <li>@Html.ActionLink("Profilim", "Profil","Liste")</li>
                            <li>@Html.ActionLink("Şifre Değiştir", "Edit","Liste")</li>
                            <li>
                                @Html.ActionLink("Siparişlerim", "Home")
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="page-top-info">
                    <div class="container">
                        <h6>@Html.ActionLink("Tema Görünümü", "Index", "Home")</h6>
                        @*<div class="site-pagination">
                                <a href="">Home</a> /
                                <a href="">Shop</a> /
                            </div>*@
                    </div>
                </div>
                <div class="col-lg-8  order-2 order-lg-2 mb-5 mb-lg-0">
                    <div class="row">
                        @RenderBody()
                    </div>
                </div>
            </div>
        </div>
    </section>
    <section class="footer-section">
        <div class="social-links-warp">
            <div class="container">
                <div class="social-links">
                    <a href="" class="instagram"><i class="fa fa-instagram"></i><span>instagram</span></a>
                    <a href="" class="google-plus"><i class="fa fa-google-plus"></i><span>g+plus</span></a>
                    <a href="" class="pinterest"><i class="fa fa-pinterest"></i><span>pinterest</span></a>
                    <a href="" class="facebook"><i class="fa fa-facebook"></i><span>facebook</span></a>
                    <a href="" class="twitter"><i class="fa fa-twitter"></i><span>twitter</span></a>
                    <a href="" class="youtube"><i class="fa fa-youtube"></i><span>youtube</span></a>
                    <a href="" class="tumblr"><i class="fa fa-tumblr-square"></i><span>tumblr</span></a>
                </div>

                <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                <p class="text-white text-center mt-5">
                    Copyright &copy;
                    <script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
                </p>
                <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->

            </div>
        </div>
    </section>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <script src="~/Scripts/js/jquery-3.2.1.min.js"></script>
    <script src="~/Scripts/js/bootstrap.min.js"></script>
    <script src="~/Scripts/js/jquery.slicknav.min.js"></script>
    <script src="~/Scripts/js/owl.carousel.min.js"></script>
    <script src="~/Scripts/js/jquery.nicescroll.min.js"></script>
    <script src="~/Scripts/js/jquery.zoom.min.js"></script>
    <script src="~/Scripts/js/jquery-ui.min.js"></script>
    <script src="~/Scripts/js/main.js"></script>
    <script src="~/Content/login/js/global.js"></script>
    <script src="~/Content/login/js/global-file.js"></script>
</body>
</html>