GardenyaGirisimciKadinlar/Models/Urunler.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace GardenyaGirisimciKadinlar.Models
{
    public class Urunler
    {
        [Key]
        public int UrunID { get; set; }
        [Display(Name = "Başlık")]
        public string Baslik { get; set; }
        [Display(Name = "Açıklama")]
        public string Aciklama { get; set; }
        public string Resim { get; set; }
        public int Adet { get; set; }
        public int SatılanAdet { get; set; }
        public int Fiyat { get; set; }
        [Display(Name = "Eklenme Tarihi")]
        public DateTime EklenmeTarihi { get; set; } = DateTime.Now;
        public int AltKategoriID { get; set; }
        public virtual AltKategori AltKategori { get; set; }
        public string GirisimciID { get; set; }
        public virtual Kullanici Kullanici { get; set; }
        //public int GirisimciID { get; set; }
        //public virtual Girisimci Girisimci { get; set; }
        public virtual List<SiparisDetay> SiparisDetays { get; set; }

        //[Key]
        //public int GirisimciID { get; set; }
        //[Required]
        //public string Ad { get; set; }
        //[Required]
        //public string Soyad { get; set; }
        //[Required]
        //[StringLength(11, ErrorMessage = "TC 11 haneli olmalıdır", MinimumLength = 11)]
        //public string TC { get; set; }
        //public string Resim { get; set; }
        //[Required]
        //[DataType(DataType.PhoneNumber)]
        //public string Tel { get; set; }
        //[Required]
        //public string Adres { get; set; }
        //[Required]
        //[EmailAddress]
        //[Display(Name = "Email")]
        //public string Email { get; set; }
        //[Required]
        //[StringLength(100, ErrorMessage = "Parolanız en az 6 karakterden oluşmalıdır", MinimumLength = 6)]
        //[DataType(DataType.Password)]
        //[Display(Name = "Password")]
        //public string Parola { get; set; }
        //[DataType(DataType.Password)]
        //[Display(Name = "Confirm password")]
        //[Compare("Password", ErrorMessage = "Parola ve parola tekrar eşleşmemektedir")]
        //public string ParolaTekrar { get; set; }
        //public virtual List<Urunler> Urunlers { get; set; }
    }
}

GardenyaGirisimciKadinlar/Controllers/HomeController.cs
using GardenyaGirisimciKadinlar.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GardenyaGirisimciKadinlar.Controllers
{
    public class HomeController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        public ActionResult Index()
        {
            var result = (from u in db.Urunlers orderby u.EklenmeTarihi descending select u).Take(7).ToList();
            ViewBag.EnYeni = result;
            return View();
        }
        public ActionResult Menu()
        {
            
            return PartialView(db.Kategoris.ToList());
        }

        public ActionResult getUrunler()
        {
            
            return PartialView(db.Urunlers.Take(5).ToList());
        }
        public ActionResult getUrunlerID()
        {
            
            return PartialView(db.Urunlers.Take(5).ToList());
        }

        public ActionResult Urunler()
        {
            ViewBag.Kategoriler = db.AltKategoris.ToList();
            return PartialView(db.Urunlers.Take(30).ToList());
        }
        public ActionResult UrunDetay(int? id)
        {          ViewBag.Adet = 1;
            if (id==null)
            {
                return RedirectToAction("Index", "Home");
            }
            else
            {
                var result = (from u in db.Urunlers
                              join k in db.AltKategoris on u.AltKategoriID equals k.AltKategoriID
                              join g in db.Users on u.GirisimciID equals g.Id
                              where u.UrunID == id
                              select new UrunlerGirisimciAltKatViewModel()
                              {
                                  GirisimciAdi=g.Ad+" "+g.Soyad,
                                  AltKategoriAdi=k.AltKategoriAdi,
                                  Aciklama=u.Aciklama,
                                  Baslik=u.Baslik,
                                  Fiyat=u.Fiyat,
                                  Resim=u.Resim,
                                  Adet=1,
                                  UrunID=u.UrunID
                              }).FirstOrDefault();
                    return View(result);
            }
  
        }



    }
}

GardenyaGirisimciKadinlar/Controllers/ShoppingCartController.cs
using GardenyaGirisimciKadinlar.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GardenyaGirisimciKadinlar.Controllers
{
    public class ShoppingCartController : Controller
    {
        // GET: ShoppingCart
        private ApplicationDbContext db = new ApplicationDbContext();
        public ActionResult Index()
        {
            //View modelimle çalışıp bana bilgi verecek
            var cart = ShoppingCart.GetCart(this.HttpContext);
            var cartviewmodel = new ShoppingCardViewModel
            {
                CartItems = cart.GetCartItems(),
                CartTotal = cart.GetTotal(),

            };

           
            return View(cartviewmodel);
        }
        //addCart
        public ActionResult AddToCart([Bind(Include = "UrunID,Adet")] Urunler urunler)
        {
            var eklenen = db.Urunlers.FirstOrDefault(x => x.UrunID == urunler.UrunID);
            eklenen.Adet = urunler.Adet;
            var cart = ShoppingCart.GetCart(this.HttpContext);
            cart.AddToCart(eklenen);
            return RedirectToAction("Index");

        }
        //RemoveCart
        public ActionResult RemoveToCart(int id)
        {
            //item countu değişti
            //total amount değişti
            //view model mesaj vermiştik bunu da gönderelim

            //var kaldir = db.Products.FirstOrDefault(x => x.ProductID == id).ProductID;
            var cart = ShoppingCart.GetCart(this.HttpContext);
            //Kullanıcıya mesaj vermek istiyorum
            //şu isimli ürün sepetinizden kaldırıldı gibi
            //o yüzden şunu yazmam gerekecek
            string itemname = db.Carts.FirstOrDefault(x => x.RecordID == id).Urunler.Baslik;//Ürünün adını getirmek için yazdık

            int itemcount = cart.RemoveFromCart(id);
            var result = new ShoppingCartRemoveViewModel
            {
                Message = Server.HtmlEncode(itemname) + " sepetinizden başarıyla kaldırıldı",
                CartTotal = cart.GetTotal(),
                Count = cart.GetCount(),
                ItemCount = itemcount
            };
            return Json(result);

        }
        //Cart Summary
        //Partial view olabilir
        public ActionResult CartSummary()
        {
            var cart = ShoppingCart.GetCart(this.HttpContext);
            ViewData["CartCount"] = cart.GetCount();
            return PartialView("CartSummary");
        }
    }
}

GardenyaGirisimciKadinlar/Controllers/UrunlerKategoriController.cs
using GardenyaGirisimciKadinlar.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GardenyaGirisimciKadinlar.Controllers
{
    public class UrunlerKategoriController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        // GET: UrunlerKategori

            
        public ActionResult Index(int? id, int? kid)
        {
            if (id==null)
            {
                return View("Index","Home");
            }
            var result = (from  ak in db.AltKategoris 
                          where ak.KategoriID == id
                          select new UrunlerGirisimciAltKatViewModel {
                              AltKategoriID=ak.AltKategoriID,
                               AltKategoriAdi=ak.AltKategoriAdi,
                              KategoriID=ak.KategoriID
                          }  ).ToList();
            if (kid!=null)
            {
                var urunler = (from u in db.Urunlers
                               where u.AltKategoriID == kid
                               select new UrunlerGirisimciAltKatViewModel
                               {
                                   UrunID = u.UrunID,
                                   Baslik = u.Baslik,
                                   Aciklama = u.Aciklama,
                                   Resim = u.Resim,
                                   Fiyat = u.Fiyat
                               }).ToList();
                ViewBag.urunler = urunler;
            }
            else
            {
                var urunler = db.Urunlers.Where(x => db.AltKategoris.Select(i => i.AltKategoriID).Contains(x.AltKategoriID));

            }
            return View(result);
        }

        public ActionResult Urunler(int id)
        {
 
            var result = (from ak in db.AltKategoris join
                          u in db.Urunlers on ak.AltKategoriID equals u.AltKategoriID
                          where u.AltKategoriID == id select ak
                                  
                        ).ToList();


            ViewBag.KatID = id;
            return PartialView(result);
        }
        public ActionResult AltKategoriler(int id=1)
        {
   
            var result = (from k in db.Kategoris
                          join ak in db.AltKategoris on k.KategoriID equals ak.KategoriID
                          where k.KategoriID == id
                          select new UrunlerGirisimciAltKatViewModel {
                              AltKategoriID=ak.AltKategoriID,
                              AltKategoriAdi=ak.AltKategoriAdi
                          }
                        ).ToList();
            ViewBag.KatID = id;
            return PartialView(result);
        }
    }
}

GardenyaGirisimciKadinlar/Controllers/UrunlersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using GardenyaGirisimciKadinlar.Models;
using Microsoft.AspNet.Identity;

namespace GardenyaGirisimciKadinlar.Controllers
{
    public class UrunlersController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Urunlers
        [Authorize(Roles = "Admin")]
        public ActionResult TumUrunler()
        {
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Login", "Account");
            }
            var urunlers = db.Urunlers.Include(u => u.AltKategori);

            return View(urunlers.ToList());
        }
        [Authorize(Roles = "Girisimci")]
        public ActionResult Index()
        {
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Login", "Account");
            }
            var userid = User.Identity.GetUserId();
            

            var urunlers = db.Urunlers.Where(x=>x.GirisimciID==userid).ToList();
            return View(urunlers.ToList());
        }

        // GET: Urunlers/Details/5
        [Authorize(Roles = "Girisimci")]
        public ActionResult Details(int? id)
        {

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Urunler urunler = db.Urunlers.Find(id);
            string rsm = "../" + urunler.Resim;
            ViewBag.Resim = rsm;
            if (urunler == null)
            {
                return HttpNotFound();
            }
            return View(urunler);
        }

        // GET: Urunlers/Create
        [Authorize(Roles = "Girisimci")]
        public ActionResult Create()
        {
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Login", "Account");
            }
            ViewBag.AltKategoriID = new SelectList(db.AltKategoris, "AltKategoriID", "AltKategoriAdi");
            //var userid = User.Identity.GetUserId();

            return View();
        }

        // POST: Urunlers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "UrunID,Baslik,Aciklama,Adet,Fiyat,AltKategoriID")] Urunler urunler, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                if (file != null)
                {
                    WebImage img = new WebImage(file.InputStream);
                    FileInfo fotoinfo = new FileInfo(file.FileName);
                    string newfoto = Guid.NewGuid().ToString() + fotoinfo.Extension;
                    img.Resize(500, 775);
                    img.Save("~/Upload/Products/" + newfoto);
                    urunler.Resim = "../Upload/Products/" + newfoto;
                    urunler.EklenmeTarihi = DateTime.Now;

                }
                var userid = User.Identity.GetUserId();
                urunler.GirisimciID =userid;

                db.Urunlers.Add(urunler);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.AltKategoriID = new SelectList(db.AltKategoris, "AltKategoriID", "AltKategoriAdi", urunler.AltKategoriID);
            return View(urunler);
        }

        // GET: Urunlers/Edit/5
        [Authorize(Roles = "Girisimci")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Urunler urunler = db.Urunlers.Find(id);
            if (urunler == null)
            {
                return HttpNotFound();
            }
            ViewBag.AltKategoriID = new SelectList(db.AltKategoris, "AltKategoriID", "AltKategoriAdi", urunler.AltKategoriID);
            return View(urunler);
        }

        // POST: Urunlers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "UrunID,Baslik,Aciklama,Adet,Fiyat,EklenmeTarihi,AltKategoriID")] Urunler urunler, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                if (file != null && file.ContentLength>0)
                {
                    WebImage img = new WebImage(file.InputStream);
                    FileInfo fotoinfo = new FileInfo(file.FileName);
                    string newfoto = Guid.NewGuid().ToString() + fotoinfo.Extension;
                    img.Resize(500, 775);
                    img.Save("~/Upload/Products/" + newfoto);
                    urunler.Resim = "../Upload/Products/" + newfoto;

                }
                var userid = User.Identity.GetUserId();
                urunler.GirisimciID = userid;
                db.Entry(urunler).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.AltKategoriID = new SelectList(db.AltKategoris, "AltKategoriID", "AltKategoriAdi", urunler.AltKategoriID);
            return View(urunler);
        }

        // GET: Urunlers/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Urunler urunler = db.Urunlers.Find(id);
            string rsm = "../" + urunler.Resim;
            ViewBag.Resim =rsm ;
            if (urunler == null)
            {
                return HttpNotFound();
            }
            return View(urunler);
        }

        // POST: Urunlers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Urunler urunler = db.Urunlers.Find(id);
            db.Urunlers.Remove(urunler);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

GardenyaGirisimciKadinlar/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}


<!-- Hero section end -->
<!-- Features section -->
<section class="hero-section">
    <div class="hero-slider owl-carousel">
        <div class="hs-item set-bg" data-setbg="img/bg.jpg">
            <div class="container">
                <div class="row">
                    <div class="col-xl-6 col-lg-7 text-white">
                        <span>New Arrivals</span>
                        <h2>denim jackets</h2>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Quis ipsum sus-pendisse ultrices gravida. Risus commodo viverra maecenas accumsan lacus vel facilisis. </p>
                        <a href="#" class="site-btn sb-line">DISCOVER</a>
                        <a href="#" class="site-btn sb-white">ADD TO CART</a>
                    </div>
                </div>
                <div class="offer-card text-white">
                    <span>from</span>
                    <h2>$29</h2>
                    <p>SHOP NOW</p>
                </div>
            </div>
        </div>
        <div class="hs-item set-bg" data-setbg="img/bg-2.jpg">
            <div class="container">
                <div class="row">
                    <div class="col-xl-6 col-lg-7 text-white">
                        <span>New Arrivals</span>
                        <h2>denim jackets</h2>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Quis ipsum sus-pendisse ultrices gravida. Risus commodo viverra maecenas accumsan lacus vel facilisis. </p>
                        <a href="#" class="site-btn sb-line">DISCOVER</a>
                        <a href="#" class="site-btn sb-white">ADD TO CART</a>
                    </div>
                </div>
                <div class="offer-card text-white">
                    <span>from</span>
                    <h2>$29</h2>
                    <p>SHOP NOW</p>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="slide-num-holder" id="snh-1"></div>
    </div>
</section>

<!-- Features section end -->
<!-- letest product section -->
<section >
    <div >
        <div class="features-section">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-4 p-0 feature">
                        <div class="feature-inner">
                            <div class="feature-icon">
                                <img src="~/Content/img/icons/1.png" alt="#">
                            </div>
                            <h2><a href="#" style="color:black">En Hesaplı Ürünler</a></h2>
                        </div>
                    </div>
                    <div class="col-md-4 p-0 feature">
                        <div class="feature-inner">
                            <div class="feature-icon">
                                <img src="~/Content/img/icons/2.png" alt="#">
                            </div>
                            <h2><a href="#" style="color:black">En Çok Beğenilen Ürünler</a></h2>
                        </div>
                    </div>
                    <div class="col-md-4 p-0 feature">
                        <div class="feature-inner">
                            <div class="feature-icon">
                                <img src="~/Content/img/icons/3.png" alt="#">
                            </div>
                            <h2><a href="#" style="color:black">En Yeni Ürünler</a></h2>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="top-letest-product-section">
            <div class="container">
                <div class="section-title">
                    <h2>EN YENİ ÜRÜNLER</h2>
                </div>
                <div class="product-slider owl-carousel">
                    @if (ViewBag.EnYeni != null)
                    {
                        foreach (var item in ViewBag.EnYeni)
                        {
                            <div class="product-item">
                                <div class="pi-pic">
                                    <img src="../@item.Resim" alt="" height="300px !important">
                                    <div class="pi-links">
                                        <a href="@Url.Action("UrunDetay", "Home", new { id = item.UrunID })" class="add-card"><i class="flaticon-bag"></i><span> Ürünü İncele</span></a>
                                        <a href="#" class="wishlist-btn"><i class="flaticon-heart"></i></a>
                                    </div>
                                </div>
                                <div class="pi-text">
                                    <h6>@item.Fiyat<span class="simge-tl">&#8378;</span></h6>
                                    <p>@item.Baslik </p>
                                </div>
                            </div>
                        }
                    }


                </div>
            </div>
        </div>
    </div>
</section>
@{ Html.RenderAction("Urunler", "Home"); }

<!-- Product filter section end -->
<!-- Banner section -->
<section class="banner-section">
    <div class="container">
        <div class="banner set-bg" data-setbg="img/banner-bg.jpg">
            <div class="tag-new">NEW</div>
            <span>New Arrivals</span>
            <h2>STRIPED SHIRTS</h2>
            <a href="#" class="site-btn">SHOP NOW</a>
        </div>
    </div>
</section>

GardenyaGirisimciKadinlar/Views/Home/Menu.cshtml
@model IEnumerable<GardenyaGirisimciKadinlar.Models.Kategori>

<nav class="main-navbar">
    <div class="container">
        <!-- menu -->
        <ul class="main-menu">

            @foreach (var item in Model)
            {
                if (item.KategoriAdi=="Anasayfa")
                {
                    <li>
                        @Html.ActionLink(item.KategoriAdi, "Index", "Home", new { id = item.KategoriID }, new { @class = "urun" })
                    </li>
                }
                else
                {
                    <li>
                        @Html.ActionLink(item.KategoriAdi, "Index", "UrunlerKategori", new { id = item.KategoriID }, new { @class = "urun" })
                    </li>}

            }
        </ul>
    </div>
</nav>

GardenyaGirisimciKadinlar/Views/Home/UrunDetay.cshtml
@model GardenyaGirisimciKadinlar.Models.UrunlerGirisimciAltKatViewModel

@{
    ViewBag.Title = "UrunDetay";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<section class="product-section">
    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                <div @*class="product-pic-zoom"*@>
                    <img src="../@Html.DisplayFor(modelItem => Model.Resim)" class="product-big-img"alt="">
                </div>

            </div>
            <div class="col-lg-6 product-details">
                <h2 class="p-title">@Html.DisplayFor(model => model.Baslik)</h2>
                <h3 class="p-price">@Html.DisplayFor(model => model.Fiyat)<span class="simge-tl">&#8378;</span></h3>
                <h4 class="p-stock">Kategori: @Html.DisplayFor(model => model.AltKategoriAdi)</h4>
                <div class="p-rating">
                    <i class="fa fa-star-o"></i>
                    <i class="fa fa-star-o"></i>
                    <i class="fa fa-star-o"></i>
                    <i class="fa fa-star-o"></i>
                    <i class="fa fa-star-o fa-fade"></i>
                </div>

                @*</div>*@
                @using (Html.BeginForm("AddToCart", "ShoppingCart"))
                {
                    <div class="quantity">
                        <p>Adet</p>
                        <div class="pro-qty">
                            @*<input type="text" value="1" name="@Html.DisplayFor(model => model.Adet)">*@
                            @Html.EditorFor(model => model.Adet)
                        </div>
                    </div>
                    @Html.HiddenFor(model => model.UrunID)
                    @*@Html.ActionLink("Sepete Ekle", "AddToCart", "ShoppingCart", htmlAttributes: new { @class = "site-btn" })*@
                    <input type="submit" value="Sepete Ekle" class="site-btn" />
                }
   
                <div id="accordion" class="accordion-area">
                    <div class="panel">
                        <div class="panel-header" id="headingOne">
                            <button class="panel-link active" data-toggle="collapse" data-target="#collapse1" aria-expanded="true" aria-controls="collapse1">Ürün Bİlgileri</button>
                        </div>
                        <div id="collapse1" class="collapse show" aria-labelledby="headingOne" data-parent="#accordion">
                            <div class="panel-body">
                                @Html.DisplayFor(model => model.Aciklama)
                                <br />
                                Girişimci Adı:@Html.DisplayFor(model => model.GirisimciAdi)
                            </div>
                        </div>
                    </div>

                </div>
                <div class="social-sharing">
                    <a href=""><i class="fa fa-google-plus"></i></a>
                    <a href=""><i class="fa fa-pinterest"></i></a>
                    <a href=""><i class="fa fa-facebook"></i></a>
                    <a href=""><i class="fa fa-twitter"></i></a>
                    <a href=""><i class="fa fa-youtube"></i></a>
                </div>
            </div>
    </div>
    </div>
</section>

GardenyaGirisimciKadinlar/Views/Home/Urunler.cshtml
@model IEnumerable<GardenyaGirisimciKadinlar.Models.Urunler>

<section class="product-filter-section">
    <div class="container">
        <div class="section-title">
            <h2></h2>
        </div>

        <div class="row">
            @foreach (var item in Model)
            {
                <div class="col-lg-3 col-sm-6">
                    <div class="product-item">
                        <div class="pi-pic">
                            <img src="../@Html.DisplayFor(modelItem => item.Resim)" alt="" height="300px !important">
                            <div class="pi-links">
                                <a href="@Url.Action("UrunDetay", "Home", new { id = item.UrunID })" class="add-card"><i class="flaticon-bag"></i><span> Ürünü İncele</span></a>
                                <a href="#" class="wishlist-btn"><i class="flaticon-heart"></i></a>
                            </div>
                        </div>
                        <div class="pi-text">
                            <h6> @Html.DisplayFor(modelItem => item.Fiyat)<span class="simge-tl">&#8378;</span></h6>
                            <p> @Html.DisplayFor(modelItem => item.Baslik)</p>
                        </div>

                    </div>
                </div>
            }

        </div>


        <ul class="product-filter-menu" style="margin-top:50px;">
            @foreach (var item in ViewBag.Kategoriler)
            {
                <li><a href="#">@item.AltKategoriAdi</a></li>
            }

        </ul>
    </div>
</section>